apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend #Sets deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 3a7jouokyffroregistry.azurecr.io/venkatp/backend:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8000 #Exposes container port
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: url
      imagePullSecrets:
        - name: docker-pull-secret                         